// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Settings.proto

package com.example.application;

public final class SettingsOuterClass {
  private SettingsOuterClass() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  static {
  }

  // @@protoc_insertion_point(outer_class_scope)
}
