// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Settings.proto

package com.example.application;

public interface SettingsOrBuilder extends
    // @@protoc_insertion_point(interface_extends:Settings)
    com.google.protobuf.MessageLiteOrBuilder {

  /**
   * <code>int32 example_counter = 1;</code>
   */
  int getExampleCounter();
}
